Repository testcontainers/testcontainers-rs, pull requests merged in 2019-02, with the labels that each got.

#58 Add generic image
  .travis.yml
  Cargo.toml
  images/generic/Cargo.toml
  images/generic/README.md
  images/generic/src/image.rs
  images/generic/src/lib.rs
  testcontainers/Cargo.toml
  testcontainers/src/lib.rs
  testcontainers/tests/images.rs
Labels: review

#64 Add release checklist
  RELEASE_CHECKLIST.md
Labels: added-mid-sprint, review

#63 Remove code coverage from travis
  .travis.yml
Labels: review

#38 Add a postgres image
  .travis.yml
  Cargo.toml
  images/postgres/Cargo.toml
  images/postgres/README.md
  images/postgres/src/image.rs
  images/postgres/src/lib.rs
  testcontainers/Cargo.toml
  testcontainers/src/lib.rs
  testcontainers/tests/images.rs
Labels: review

#67 Add .mergify.yml
  .mergify.yml
Labels: automagically-mergify-this, review

#69 Allow configuration of acceptnonstdtxn option for Bitcoin Core
  images/coblox_bitcoincore/src/image.rs
Labels: automagically-mergify-this, review

#70 Bump tc_core version to 0.3.0, testcontainers to 0.5.1
  RELEASE_CHECKLIST.md
  cli_client/Cargo.toml
  core/Cargo.toml
  images/coblox_bitcoincore/Cargo.toml
  images/dynamodb_local/Cargo.toml
  images/elasticmq/Cargo.toml
  images/generic/Cargo.toml
  images/parity_parity/Cargo.toml
  images/postgres/Cargo.toml
  images/redis/Cargo.toml
  images/trufflesuite_ganachecli/Cargo.toml
  testcontainers/Cargo.toml
Labels: review

#72 Fix typo + ask for `test --all`
  RELEASE_CHECKLIST.md
Labels: automagically-mergify-this, review
